[package]

name = "rust-ascii-march"
version = "0.1.0"
authors = ["Peter Jacobs <peter@crespyl.net>"]

[dependencies]
rand = "0.3"
noise = "0.5"
rustbox = "0.9"
num = "0.1"

[[bin]]
name = "ascii-march"
path = "src/main.rs"
